[Contributing Rule Change] Enhance contributing guide
Anduin2017/HowToCook pull request #104
Opened 2022-02-19 10:02 UTC by recolic

2022-02-19 10:16 UTC, recolic commented on CONTRIBUTING.md
> +Add some motivation here. @Anduin
Note: do not merge until project author reviews/add the motivation.

2022-02-19 10:17 UTC, recolic commented on .github/workflows/ci.yml
> +        run: mdl *.md -r ~MD009,~MD029,~MD036,~MD024
如果有人知道怎样将br_space这个参数设置为2，请添加comment.

2022-02-19 11:07 UTC, bobby285271 commented on .github/workflows/ci.yml
> +        run: mdl *.md -r ~MD009,~MD029,~MD036,~MD024
应该是创建一个 style（有 [文档](https://github.com/markdownlint/markdownlint/blob/master/docs/creating_styles.md) 和 [例子](https://github.com/markdownlint/markdownlint/blob/master/.mdl_style.rb)），然后 `mdl -s /path/to/style.rb *.md`。

2022-02-19 11:50 UTC, recolic commented on .github/workflows/ci.yml
> +        run: mdl *.md -r ~MD009,~MD029,~MD036,~MD024
@bobby285271 这是一个好主意，但这不是这个PR要解决的问题）
这里只是做了最小的必要改动，使得这个PR能merge进去。可以再开一个新的issue来实现这个style功能

2022-02-19 12:39 UTC, Anduin2017 requested changes
其实我是觉得描述太多的话，其它人无法快速上手或把已有菜谱快速修改并签入。建议删掉一些无意义的感想，仅保留最简明的要求

2022-02-19 15:34 UTC, Anduin2017 commented
Close。因为已经使用模板。

PR里的文字内容将移植到模板中。

2022-02-20 09:19 UTC, recolic commented
这个PR刚开始是为`贡献者`和`维护者`设计的, 简明易懂的模板确实满足了贡献者的需求. 

但我修改了这个指南, 使它仍然为`维护者`服务. 我主观认为有必要以正式而严谨的语言, 来保留仓库的principle. 
please review it again)

2022-02-20 09:20 UTC, Anduin2017 approved these changes

2022-02-20 09:20 UTC, merged