新增“葱油桂鱼做法”，内附详细步骤
Anduin2017/HowToCook pull request #1060
Opened 2022-06-26 13:15 UTC by taiziye

## 注意

Pull Request 提交后，预计 1 分钟内将会得到自动化格式检查的结果。只有通过自动化检查的 Pull Request 才会被人工审核。

- [ ] 请确保此 Pull Request 能够通过自动化代码检查。

## 签署

必须签署下面的对话框才能开始审核。

### HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议

菜谱在签入前，必须确保其可以**直接声明进入 "公共领域"（public domain)**。这意味着一旦合并后，任何人都**可以**自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，**无论**是出于**商业目的**还是**非商目的**，以及**任何**手段。

- [ ] 我确保了我的内容不涉及版权内容，并且授权它 The Unlicense 协议。

2022-06-26 16:00 UTC, Anduin2017 requested changes
不在文章中引用这些图片嘛？

2022-06-26 16:00 UTC, Anduin2017 commented on dishes/aquatic/葱油桂鱼/葱油桂鱼.md
> +
不在文章中引用这些图片嘛？

2022-06-26 16:07 UTC, taiziye commented on dishes/aquatic/葱油桂鱼/葱油桂鱼.md
> +
下一次PR新菜谱的时候一并调整

2022-06-26 16:20 UTC, bobby285271 commented
对了看到你连续开和关了好几个 PR，其实不需要的，你如果需要修改这个 PR 的内容直接在 https://github.com/taiziye/HowToCook/tree/master 上修改就行了，所有变更会自动同步过来的，我们在合并时会把所有改动压缩成单个提交的 :eyes:

2022-06-26 16:24 UTC, taiziye commented
> 

是的，我也是后来发现了的这个带流水线功能有这个自动更改同步的，因为是第一次提交，后面就知道了

2022-06-28 10:29 UTC, Anduin2017 commented
暂时不允许合并此PR。此PR增加了大量图片。考虑到图片一旦签入仓库，将无论如何都无法撤回。这将永久性的增加仓库的clone耗时和磁盘占用，并显著阻碍其它贡献者同步仓库。建议仅增加1--5张必要的图片。

2022-06-28 10:29 UTC, Anduin2017 requested changes
暂时不允许合并此PR。此PR增加了大量图片。考虑到图片一旦签入仓库，将无论如何都无法撤回。这将永久性的增加仓库的clone耗时和磁盘占用，并显著阻碍其它贡献者同步仓库。建议仅增加1--5张必要的图片。

2022-07-31 02:11 UTC, taiziye commented
删除了一些多余的照片

2022-07-31 02:13 UTC, closed without merging