添加了排骨苦瓜汤
Anduin2017/HowToCook pull request #1245
Opened 2023-05-10 01:39 UTC by qq836838507

## 注意

Pull Request 提交后，预计 1 分钟内将会得到自动化格式检查的结果。只有通过自动化检查的 Pull Request 才会被人工审核。

- [x] 请确保此 Pull Request 能够通过自动化代码检查。

## 签署

必须签署下面的对话框才能开始审核。

### HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议

菜谱在签入前，必须确保其可以**直接声明进入 "公共领域"（public domain)**。这意味着一旦合并后，任何人都**可以**自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，**无论**是出于**商业目的**还是**非商目的**，以及**任何**手段。

- [x] 我确保了我的内容不涉及版权内容，并且授权它 The Unlicense 协议。

2023-07-11 09:11 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +排骨苦瓜汤是一道味道鲜美且容易烹饪的汤。不过汤的烹饪时间都较长，一般来说最好提前4个小时开始进行准备。
```suggestion

排骨苦瓜汤是一道味道鲜美且容易烹饪的汤。不过汤的烹饪时间都较长，一般来说最好提前4个小时开始进行准备。
```

2023-07-11 09:11 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +排骨苦瓜汤是一道味道鲜美且容易烹饪的汤。不过汤的烹饪时间都较长，一般来说最好提前4个小时开始进行准备。
```console
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:1: MD022 Headers should be surrounded by blank lines
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:3: MD022 Headers should be surrounded by blank lines
```

2023-07-11 09:12 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +可选工具
```suggestion

可选工具
```

2023-07-11 09:12 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +- 虾皮
```suggestion
- 虾皮

```

2023-07-11 09:12 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +- 虾皮
```
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:11: MD022 Headers should be surrounded by blank lines
```

2023-07-11 09:13 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +## 操作
```suggestion

## 操作
```

2023-07-11 09:13 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +## 操作
```
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:17: MD032 Lists should be surrounded by blank lines
```

2023-07-11 09:13 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +每份：
```suggestion
每份：

```

2023-07-11 09:14 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +## 附加内容
```suggestion

## 附加内容

```

2023-07-11 09:15 UTC, littlewhitecloud commented on dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md
> +## 附加内容
```console
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:29: MD032 Lists should be surrounded by blank lines
./dishes/soup/排骨苦瓜汤/排骨苦瓜汤.md:31: MD032 Lists should be surrounded by blank lines
```

2023-07-11 09:15 UTC, littlewhitecloud requested changes
希望以下Request changes能帮助你通过检查~

2023-07-12 10:47 UTC, littlewhitecloud commented
?

2023-07-13 08:30 UTC, Anduin2017 approved these changes

2023-07-13 08:32 UTC, merged