Create 水煮玉米.md
Anduin2017/HowToCook pull request #125
Opened 2022-02-20 06:57 UTC by WyattJia

2022-02-20 07:07 UTC, Anduin2017 commented
记得添加readme到菜谱的引用。

2022-02-20 07:16 UTC, Anduin2017 approved these changes
请阅读贡献模板：https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md

2022-02-20 07:16 UTC, Anduin2017 commented on dishes/breakfast/水煮玉米.md
> +- 根据口味加适量糖
不允许出现词汇“适量”。这里可以给出参考的添加量范围。

2022-02-20 07:16 UTC, Anduin2017 commented on dishes/breakfast/水煮玉米.md
> +- 煮熟后沥干水分，冷却后食用。
在哪一步加糖？

2022-02-20 07:16 UTC, Anduin2017 commented on dishes/breakfast/水煮玉米.md
> +- 适量带皮玉米
不允许出现“适量”

2022-02-20 08:41 UTC, recolic approved these changes

2022-02-20 09:18 UTC, Anduin2017 requested changes
补充一下精确数值。

2022-02-21 01:57 UTC, WyattJia commented
@Anduin2017 I have been resolved issue, please review my change.

2022-02-21 02:08 UTC, Anduin2017 approved these changes

2022-02-21 02:09 UTC, merged