Add: 蒜黄(韭黄)炒鸡蛋
Anduin2017/HowToCook pull request #131
Opened 2022-02-20 09:34 UTC by Erosion2020

2022-02-20 09:37 UTC, Anduin2017 requested changes
文件路径不规范。应该放在分类后的文件夹中。

2022-02-20 11:21 UTC, recolic commented on 蒜黄(韭黄)炒鸡蛋.md
> +锅中加入5ml油，然后倒入葱花，不停翻炒爆出葱香味，倒入蒜黄，加入2g食用盐、1g鸡精
如果能加入时间的描述就更好了. 例如`然后倒入葱花，不停翻炒约10秒爆出葱香味，倒入蒜黄` or `大火不停翻炒直至蒜黄(韭黄)茎发软(约一分钟), 倒入煎好的鸡蛋`.

2022-02-21 05:36 UTC, RobertIndie commented on 蒜黄(韭黄)炒鸡蛋.md
> +大葱一段 约10cm段
```suggestion
* 大葱一段 约10cm段
```
建议使用markdown写法，下同。

2022-02-21 05:36 UTC, RobertIndie commented on 蒜黄(韭黄)炒鸡蛋.md
> +食用油
这里是否应该描述总的用油量。

2024-06-04 15:09 UTC, TarushChaturvedi commented
麻婆豆腐补充，添加可选用料牛肉与花椒油/藤椒油

2025-01-16 06:23 UTC, closed without merging