水煮肉片;
Anduin2017/HowToCook pull request #166
Opened 2022-02-21 07:20 UTC by QYDIY

2022-02-21 07:38 UTC, Anduin2017 requested changes
请参考模板：https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1

2022-02-21 07:38 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +- 食用盐适量
这个菜谱集中不允许出现`适量`这个不能精准定量的词。

2022-02-21 07:38 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +2. 锅洗干净，加入适量底油烧至6层热，加入制作好的姜蒜红泡椒，爆香后加入豆瓣10克，开小火把豆瓣爆香炒出红油。
步骤结束时必须注明结束的判断标准。

2022-02-22 02:31 UTC, anois commented
@QYDIY 对原 commit 的修改，应该使用 `git commit --amend` 进行提交（噪音不应该体现在 commit log 中，这三个 commit（这个 PR）实际上对于这个仓库，只做了一件事就是 `Create  水煮肉片.md`），不然会导致 commit 历史变得极其丑陋。建议参考 https://github.com/Anduin2017/HowToCook/pull/226#issuecomment-1047353092 进行修复。

2022-02-22 05:19 UTC, Anduin2017 requested changes
您好，感谢贡献！但是看起来它的内容格式和约束的标准差距很大。请您重新从[模板文件](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1)复制来得到空菜谱，再修改内容为您的菜谱。不要直接编写新的文件。您先改改我再重新review。

2022-02-22 05:19 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +1. 锅烧热，放入100克植物油烧至6层热，加入适量青花椒、干辣椒爆香，配菜下锅，加入1克食用盐，炒制断生，盛入碗中垫底备用。
不允许出现适量。

2022-02-22 05:19 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +4. 汤汁开后，开小火将腌制好的肉片分开依次下锅，然后开中火将肉片烫熟，用锅铲轻轻推动一下避免粘连，待汤汁烧开，肉片熟后捞出放入碗中配菜上，再将原汤倒入适量。
不允许出现适量。

2022-02-22 05:19 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +- 垫底的蔬菜根据自己口味选择。
请给出选择范围。

2022-02-22 05:19 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +- 特别注意肉的腌制，保证肉滑嫩。
注意什么？

2022-02-22 05:19 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片.md
> +- 植物油 280克 （根据情况选择）
如何`根据情况选择`？

2022-02-22 07:30 UTC, Anduin2017 approved these changes

2022-02-22 07:30 UTC, merged