完善披萨饼皮制作相关信息
Anduin2017/HowToCook pull request #206
Opened 2022-02-21 13:40 UTC by i6u

1. 修改错别字
2. 更新 README

2022-02-21 14:50 UTC, Anduin2017 approved these changes

2022-02-21 14:51 UTC, Anduin2017 commented
Conflict.

2022-02-22 03:03 UTC, i6u commented
fix conflict.

2022-02-22 05:16 UTC, Anduin2017 requested changes
您好，感谢贡献！但是看起来它的内容格式还有点儿小毛病。您先改改我再重新review。

2022-02-22 05:16 UTC, Anduin2017 commented on README.md
>  * [披萨饼皮](./dishes/staple/pizza/披萨饼皮.md)
一旦合并就会产生两个披萨饼皮。这不太合理。

2022-02-22 05:16 UTC, Anduin2017 commented on dishes/staple/米饭.md
> +* 江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的**一半的一半**。
一旦合并，就会产生过多的分类和文字。如果您要修改这里，请重新梳理这些的文字。

2022-02-22 05:25 UTC, i6u commented on README.md
>  * [披萨饼皮](./dishes/staple/pizza/披萨饼皮.md)
我没发现这里的问题，我再仔细看下

2022-02-22 05:27 UTC, i6u commented on dishes/staple/米饭.md
> +* 江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的**一半的一半**。
这个问题指的是 README 里关于披萨分类的问题吗？过得分类如果让人感到困惑，我把归到主食里吧

2022-02-22 05:32 UTC, Anduin2017 requested changes
一点小问题。没别的问题了。您再稍微改改，我就直接合并了。

2022-02-22 05:32 UTC, Anduin2017 commented on dishes/staple/米饭.md
> +* 江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的**一半的一半**。
不是，这里已经有了：

```
* 江南米，米和水放在电饭煲的容器内，食指触及米时，水量能刚好没过食指的第一个指截的**一半的一半**。
* 北方大米，米和水放在电饭煲的容器内，食指触及米，水量能刚好没过食指的第一个指截。
```

你却在试图把它改成：

```
* 江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的**一半的一半**。
* 北方大米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截。
* 江南米，米和水放在电饭煲的容器内，食指触及米时，水量能刚好没过食指的第一个指截的一半。
* 江南米，米和水放在电饭煲的容器内，食指触及米时，水量能刚好没过食指的第一个指截的**一半的一半**。
* 北方大米，米和水放在电饭煲的容器内，食指触及米，水量能刚好没过食指的第一个指截。
```

我不理解……

2022-02-22 05:33 UTC, i6u commented on README.md
>  * [披萨饼皮](./dishes/staple/pizza/披萨饼皮.md)
好的，我修改完成后重新提 pr

2022-02-22 05:33 UTC, Anduin2017 commented
算了。 我感觉你这个PR里的commits已经乱得不得了了。您直接重新拉一下最新的master，重新checkout修改吧。

2022-02-22 05:33 UTC, closed without merging

2022-02-22 05:33 UTC, i6u commented on dishes/staple/米饭.md
> +* 江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的**一半的一半**。
好的

2022-02-22 05:35 UTC, i6u commented
> 算了。 我感觉你这个PR里的commits已经乱得不得了了。您直接重新拉一下最新的master，重新checkout修改吧。

好