Create 鲫鱼豆腐汤.md
Anduin2017/HowToCook pull request #212
Opened 2022-02-21 14:21 UTC by Hawks-eat-nothing

Add "鲫鱼豆腐汤的做法"

2022-02-21 14:46 UTC, Anduin2017 requested changes
请在Readme中添加对这道菜的引用。

2022-02-21 15:44 UTC, Anduin2017 requested changes
请从模板中创建。请不要移除必要的模板内容。

2022-02-22 05:12 UTC, Anduin2017 requested changes
您好，感谢贡献！但是看起来它的内容格式和约束的标准差距很大。请您重新从[模板文件](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1)复制来得到空菜谱，再修改内容为您的菜谱。不要直接编写新的文件。您先改改我再重新review。

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +* 所有材料按个人爱好与食量适量增减，处理食材时有条件带上一次性手套，使用之前生蔬食材建议提前洗净放置一旁保持卫生。
不允许让做菜者适量增减。

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +* 王刚教你
不要删除模板中必要的内容。

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +* 金针菇、海鲜菇
这里是顿号是或的意思吗

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +- 金针菇、海鲜菇 视个人喜好酌情添加
在什么时机添加？

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +- 豆腐 350g
形态要求？

2022-02-22 05:12 UTC, Anduin2017 commented on dishes/soup/鲫鱼豆腐汤.md
> +6. 放入枸杞，调入盐、洒入葱花或香菜。(若加香菜需要先将香菜放入碗底，然后将炖好的汤倒入碗中)。
香菜这里应当额外添加一个可选步骤。

2022-08-01 09:22 UTC, xiaoMingLong commented
鲫鱼豆腐汤的灵魂是   猪油煎鱼 煎好加开水

2025-04-23 10:25 UTC, closed without merging