Update 西红柿炒鸡蛋.md
Anduin2017/HowToCook pull request #240
Opened 2022-02-22 04:39 UTC by demongodYY

添加了**打出`鸡蛋液`**与**油热**的判定标准

2022-02-22 04:57 UTC, Anduin2017 requested changes
这个PR可能不会被允许合并。

2022-02-22 04:57 UTC, Anduin2017 commented on dishes/home-cooking/西红柿炒鸡蛋.md
> +6. 油热后（以沾了蛋液的筷子放入油中，上面的蛋液可以胀起为准），倒入 `鸡蛋液`。翻炒至鸡蛋结为固体且颜色微微发黄，即为 `半熟鸡蛋`
这个操作我不是很赞成。主要是目前来讲，油热并没有要求有明确的标准算油热。如果这里发生修改，那么所有菜谱的油热都需要重构。另外，看起来这个操作挺危险的，将蛋液浸入热油中会炸出高温液体吧？

2022-04-10 14:59 UTC, zhangzhanhui commented
## 改变葱花下锅时间以便充分吸收爆锅香味

* 炒鸡蛋出锅之后，不洗锅。
*** 锅内加少许油，将葱花爆锅至有香味；**
后续按前述既定程序进行

## 关于放糖的作用说明

放糖的作用是弱化西红柿的酸（因人而异，有人 不觉得那点酸是酸），放糖极少时会弱化西红柿的酸并有一定的提鲜作用，但是糖放多了会使西红柿炒鸡蛋偏腻甚至发甜，因此放糖的时候请根据个人喜好酌情添加。

2022-08-15 06:24 UTC, TwoAndOne commented on dishes/home-cooking/西红柿炒鸡蛋.md
> +6. 油热后（以沾了蛋液的筷子放入油中，上面的蛋液可以胀起为准），倒入 `鸡蛋液`。翻炒至鸡蛋结为固体且颜色微微发黄，即为 `半熟鸡蛋`
对于初级操作者来说，小火，冷油，下蛋液比较合适。

2025-04-23 10:25 UTC, closed without merging