Update 回锅肉.md
Anduin2017/HowToCook pull request #262
Opened 2022-02-22 07:13 UTC by znsoftm

2022-02-22 07:19 UTC, MESOLONELY submitted a review, later dismissed
LGTM

2022-02-22 07:20 UTC, Anduin2017 requested changes
您好，感谢贡献！有点儿小问题，您先改改我再重新review。

2022-02-22 07:20 UTC, Anduin2017 commented on dishes/home-cooking/回锅肉.md
> +- 陈醋 1/3勺
勺不是一个可靠的单位。请补充毫升 ml.

2022-02-22 07:20 UTC, Anduin2017 commented on dishes/home-cooking/回锅肉.md
> +- 大料 3 颗
考虑大料有大有小，颗 不是一个精准的单位。请额外补充一下重量 g。

2022-02-22 07:25 UTC, Anduin2017 approved these changes

2022-02-22 07:25 UTC, Anduin2017 requested changes
有conflict。请pull一下master。

2022-02-22 09:14 UTC, Anduin2017 approved these changes

2022-02-22 09:14 UTC, Anduin2017 commented
有conflict。请pull一下master。

2022-03-22 08:59 UTC, MESOLONELY approved these changes

2022-09-02 04:43 UTC, closed without merging