水煮肉片
Anduin2017/HowToCook pull request #268
Opened 2022-02-22 07:31 UTC by liujb

根据上个PR做内容修改，以及添加了成品图。

2022-02-22 09:26 UTC, MESOLONELY requested changes

2022-02-22 09:26 UTC, MESOLONELY commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +文中提到的勺子默认为家里用的普通的勺子，如图所示
建议补充上容积如: 文中提到的勺子默认为家里用的普通的勺子(容积约为5ml)

2022-02-22 09:26 UTC, MESOLONELY commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +- 蒜苗 3～4 棵
棵有些不太准确, 建议改为xx克, 或: 蒜苗 3～4 棵(每棵约为: xx克), 或: 蒜苗 3～4 棵(共大约 x ~ y 克)

2022-02-22 09:26 UTC, MESOLONELY commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +1. 热心的摊主切片或自己切片，如果自己切片需准备一把快刀。
Optional: 切片考虑增加厚度: 热心的摊主切片或自己切片(每片大约2mm)

2022-02-22 09:26 UTC, MESOLONELY commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +2. 切好片后使用料酒 + 大葱 + 生姜 + 盐 + 生抽/酱油 + 水淀粉等腌制10-15分钟（这个过程注意把肉和料用双手充分搅拌）。
多次使用的调料, 如「盐」应该加入每次的具体用量. 并在「### 配料」中添加.

2022-02-22 09:26 UTC, MESOLONELY commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +3. 另拿干净饭碗，调制水淀粉，大概3～5勺淀粉，接近1/2的饭碗的水，充分搅拌。
「### 配料」中淀粉为「3-4勺」, 可以考虑改为「准备的全部淀粉」

2022-02-22 09:44 UTC, Anduin2017 commented
请按照 @MESOLONELY 的建议修改。

2022-02-22 14:26 UTC, liujb commented
> 请按照 @MESOLONELY 的建议修改。

已完成修改，请review。

2022-02-22 15:25 UTC, Anduin2017 requested changes
问题不大了。但是我有一个问题：目前仓库里好像已经有一个版本的水煮肉片了。这个版本能不能和已有的版本融合，或如果不能融合，它有哪些新的特征呢？目前我们不允许把一道菜签入多个版本。

2022-02-22 15:25 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +![勺子](https://bkimg.cdn.bcebos.com/pic/d4628535e5dde711cbdf5888a7efce1b9d1661ba?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2UxNTA=,g_7,xp_5,yp_5/format,f_auto)
图片请确保符合CC0协议后，请把二进制签入仓库，这是为了避免依赖外部CDN。

2022-02-22 15:25 UTC, Anduin2017 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +3. 另拿干净饭碗，调制水淀粉，大概3～4勺淀粉（准备的全部淀粉），接近1/2的饭碗的水，充分搅拌。
不应当出现 `大概` 这种不精准的描述词。

2022-02-23 03:21 UTC, liujb commented
> 问题不大了。但是我有一个问题：目前仓库里好像已经有一个版本的水煮肉片了。这个版本能不能和已有的版本融合，或如果不能融合，它有哪些新的特征呢？目前我们不允许把一道菜签入多个版本。

当前仓库里的水煮肉片是另外的同学贡献的，我看了其中的内容写的比较简单，这个你们看吧。

2022-03-15 02:32 UTC, zouhangwithsweet commented
> > 问题不大了。但是我有一个问题：目前仓库里好像已经有一个版本的水煮肉片了。这个版本能不能和已有的版本融合，或如果不能融合，它有哪些新的特征呢？目前我们不允许把一道菜签入多个版本。
> 
> 当前仓库里的水煮肉片是另外的同学贡献的，我看了其中的内容写的比较简单，这个你们看吧。

有点东西，回头我试试

2022-06-25 01:49 UTC, lc6464 requested changes

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +- 漏勺（比较密的那种漏勺），如 [这里](https://cbu01.alicdn.com/img/ibank/O1CN01NioTtl1gd9uFViRPw_!!2206602884164-0-cib.jpg) 所示。
看起来像是淘宝的商品图片，应该不符合CC0协议。

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +- 五花肉的用量为 0.5 斤/男人 0.3 斤/女人
是否应当加入适用于青少年的用量？

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +3. 另拿干净饭碗，调制水淀粉，大概3～4勺淀粉（准备的全部淀粉），接近1/2的饭碗的水，充分搅拌。
应将制备水淀粉的方法放置在使用水淀粉的步骤之前。
:90

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +![勺子](https://bkimg.cdn.bcebos.com/pic/d4628535e5dde711cbdf5888a7efce1b9d1661ba?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2UxNTA=,g_7,xp_5,yp_5/format,f_auto)
百度百科的图片似乎并不符合CC0协议。

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +2. 切好片后使用料酒 + 大葱 + 生姜 + 盐 + 生抽/酱油 + 水淀粉等腌制10-15分钟（这个过程注意把肉和料用双手充分搅拌）。
应将制备水淀粉的方法放置在使用水淀粉的步骤之前。
:92

2022-06-25 01:49 UTC, lc6464 commented on dishes/home-cooking/水煮肉片/水煮肉片.md
> +* 刀口辣椒是这道菜的灵魂，不过确实也比较麻烦，特别是切的时候容易蹦，也可以用捣蒜的那个工具（一般是石头或者陶瓷的），具体叫啥我忘了，避免广告不贴链接了。
研钵？

2022-06-25 01:50 UTC, lc6464 commented
另外，图片可以简单裁剪、压缩一下，以减小文件大小。

2025-04-23 10:25 UTC, closed without merging