增加红烧可乐鸡翅做法
Anduin2017/HowToCook pull request #294
Opened 2022-02-22 09:07 UTC by goo1016

## Type of Change

这个 Pull Request 是在：

- [x] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## Checklist

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的原材料用量是无歧义且准确的。
  - [x] 菜品的`制作步骤`是完整(complete)的。
  - [x] 菜品的`原材料与工具`是完整(complete)的。
- [x] 我已更新 Readme 对本次修改的菜谱的引用，若是添加菜谱以外操作，请直接打勾。
- [x] 我没有破坏模板的一二级标题格式。
- [x] 我没有删除模板中必须的内容。
- [x] 我已删除干净所有的注释。

2022-02-22 09:11 UTC, Anduin2017 requested changes
有点儿小问题。

2022-02-22 09:11 UTC, Anduin2017 commented on dishes/home-cooking/红烧可乐鸡翅.md
> +* 生抽 3小勺/5只鸡翅
勺子不是一个可靠的单位。请注明毫升。

2022-02-22 09:11 UTC, Anduin2017 commented on dishes/home-cooking/红烧可乐鸡翅.md
> +2. 倒油（少许，如果炒勺的防粘性能足够优异则可以不放油），转动炒勺将油铺匀
不允许出现不精准的少许

2022-02-22 10:01 UTC, Anduin2017 commented on tips/advanced/调料计量技巧.md
> +> 茶匙（英语：Teaspoon，简称tsp）是一种常用于搅拌茶或咖啡的匙。
引入这个概念将会产生额外新的问题：其它人可能无法确定自己用的是何种勺子。

2022-04-12 00:15 UTC, ShamrockLee commented on tips/advanced/调料计量技巧.md
> +> 茶匙（英语：Teaspoon，简称tsp）是一种常用于搅拌茶或咖啡的匙。
@Anduin2017 據我所知，食譜上寫的「茶匙」與「湯匙」各是一種量匙，有相對固定的容積。

不同地區或政府對於該單位的定義可能有差異，但通常一茶匙為 5 毫升，一湯匙為 15 毫升。

我想我們可以定義這個專案使用的量匙容積，或將所有以量匙計量的體積都換成公制單位。

2022-04-12 12:56 UTC, merged