create: 上汤娃娃菜
Anduin2017/HowToCook pull request #309
Opened 2022-02-22 10:01 UTC by imaxing

## Type of Change

这个 Pull Request 是在：

- [ ] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## Checklist

- [ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [ ] 菜品的原材料用量是无歧义且准确的。
  - [ ] 菜品的`制作步骤`是完整(complete)的。
  - [ ] 菜品的`原材料与工具`是完整(complete)的。
- [ ] 我已更新 Readme 对本次修改的菜谱的引用，若是添加菜谱以外操作，请直接打勾。
- [ ] 我没有破坏模板的一二级标题格式。
- [ ] 我没有删除模板中必须的内容。
- [ ] 我已删除干净所有的注释。

2022-02-22 10:08 UTC, Anduin2017 commented
更新 Readme 对本次修改的菜谱的引用

2022-02-22 10:10 UTC, Anduin2017 requested changes
存在不精准的描述。

2022-02-22 10:10 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜.md
> +* 娃娃菜 两颗
颗 不是一个标准的单位。这里要指出参考的质量范围。

2022-02-22 10:10 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜.md
> +* 金针菇 适量(看个人喜好, 不喜欢see you tomorrow的就不放 😂)
不允许出现`适量`

2022-02-22 10:10 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜.md
> +* 皮蛋切成丁, 火腿肠或者午餐肉切成丁
建议给出 丁 的参考大小。例如 2-4 cm 的小段。

2022-02-22 10:10 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜.md
> +* 加入调味料蚝油、糖、盐、味精烧开, 根据个人口感决定娃娃菜是不是煮的烂一些。
这里要给出参考的煮的时间范围。

2022-02-22 15:26 UTC, Anduin2017 requested changes
有一丢丢小问题。请确保图片符合CC0协议后，将二进制直接checkin仓库。

2022-02-22 15:26 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜.md
> +<img src="https://tva1.sinaimg.cn/large/e6c9d24egy1gzmfw8skzhj20n20ugtfb.jpg" style="object-fit: contain;width: 100px;height: 100px;">
请使用原生markdown。请不要从CDN引用图片。

2022-02-22 15:34 UTC, imaxing commented on dishes/home-cooking/上汤娃娃菜.md
> +<img src="https://tva1.sinaimg.cn/large/e6c9d24egy1gzmfw8skzhj20n20ugtfb.jpg" style="object-fit: contain;width: 100px;height: 100px;">
已修改~

2022-02-23 06:58 UTC, Anduin2017 requested changes
描述必须绝对精确。

2022-02-23 06:58 UTC, Anduin2017 commented on dishes/home-cooking/上汤娃娃菜/上汤娃娃菜.md
> +* 加入调味料蚝油、糖、盐、味精烧开, 根据个人口感决定娃娃菜是不是煮的烂一些。
不允许根据个人口感。不允许大概。

2022-02-23 07:00 UTC, imaxing commented on dishes/home-cooking/上汤娃娃菜/上汤娃娃菜.md
> +* 加入调味料蚝油、糖、盐、味精烧开, 根据个人口感决定娃娃菜是不是煮的烂一些。
已修改~

2022-02-23 07:08 UTC, Anduin2017 approved these changes

2022-02-23 07:08 UTC, merged