feat：醋溜炸蛋
Anduin2017/HowToCook pull request #315
Opened 2022-02-22 11:01 UTC by pkwenda

增加一道家常菜：醋溜炸蛋
醋溜炸蛋是一道简单易做的菜，东北又名：烧溜白果。材料容易购买，口感酸甜，色香味俱全，用鸡蛋做出肉的口感。一般初学者只需要 1 小时即可完成，成熟之后 30 分钟内即可搞定~ 

## Type of Change

这个 Pull Request 是在：

- [ ] 增加菜谱

## Checklist

- [ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [ ] 菜品的原材料用量是无歧义且准确的。
  - [ ] 菜品的`制作步骤`是完整(complete)的。
  - [ ] 菜品的`原材料与工具`是完整(complete)的。
- [ ] 我已更新 Readme 对本次修改的菜谱的引用，若是添加菜谱以外操作，请直接打勾。
- [ ] 我没有破坏模板的一二级标题格式。
- [ ] 我没有删除模板中必须的内容。
- [ ] 我已删除干净所有的注释。

2022-02-22 11:15 UTC, Anduin2017 approved these changes
很赞！非常感谢贡献！我找不到任何问题。今天审核的PR里最完美的一个PR！💯💯💯

2022-02-22 11:17 UTC, Anduin2017 requested changes
真的这么多油吗

2022-02-22 11:17 UTC, Anduin2017 commented on dishes/home-cooking/醋溜炸蛋/醋溜炸蛋.md
> +- 食用油 500 - 1000 ML（根据锅的大小调整）
不对啊，我缕了半天。。你是要准备往锅里倒 二斤油吗？

2022-02-22 11:25 UTC, MESOLONELY requested changes

2022-02-22 11:25 UTC, MESOLONELY commented on dishes/home-cooking/醋溜炸蛋/醋溜炸蛋.md
> +- 白醋 50 克
液体建议使用毫升

2022-02-22 11:25 UTC, MESOLONELY commented on dishes/home-cooking/醋溜炸蛋/醋溜炸蛋.md
> +- 葱花 100 克
葱花 100 克是不是有些多?

2022-02-22 11:25 UTC, MESOLONELY commented on dishes/home-cooking/醋溜炸蛋/醋溜炸蛋.md
> +- 番茄酱 80 克
番茄酱 80 克是不是有些多了.

2022-02-22 11:26 UTC, pkwenda commented on dishes/home-cooking/醋溜炸蛋/醋溜炸蛋.md
> +- 食用油 500 - 1000 ML（根据锅的大小调整）
是的，就跟炸春卷，炸鸡一样，需要至少倒1/3锅的油，否则就是煎蛋了，没有蛋白的蓬松感，这个油可以重复利用的，炸完后控油，是我最爱吃的一道菜之一。

2022-02-22 11:42 UTC, pkwenda commented
看来这道菜有些争议 🤔 待我回家翻一下之前的照片，斟酌一下 葱花的用量，这个先搁置吧。

2022-03-04 18:27 UTC, Anduin2017 commented
@pkwenda

2023-04-06 04:19 UTC, closed without merging