feat:增加鱼香茄子的做法
Anduin2017/HowToCook pull request #329
Opened 2022-02-22 13:12 UTC by Whatever-An

## feat

- [ 增加鱼香茄子的做法] 增加菜谱

2022-02-22 13:51 UTC, MESOLONELY requested changes
非常高质量的提交, 感谢你的贡献! 留言了一些建议想请你做一些修改

2022-02-22 13:51 UTC, MESOLONELY commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* ���е���300ml�ͣ��������߳��ȣ�����ð���������ը����ӣ������ӱ�Ե΢�ƾ��̳�����Ϳ���ʢ���Ժ󳴲��á�
「等油温七成热（有烟冒出）」可以考虑修改为「大火热油3分钟左右至油温七成热（有烟冒出）etc. 」

2022-02-22 13:51 UTC, MESOLONELY commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* ���������ˮ����û�����ӣ����������ӡ�������֭��������ζ��֭��������з������ȣ��Ϳ�������ˡ�
适量清水可以考虑更精确一些, e.g. 「100ml左右清水至水将要没过茄子」

2022-02-23 03:53 UTC, Whatever-An commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* �Σ����ף�
下面有标注勺子的大小哟，直接说多少克的话  会不会不好计量？买称重器的人应该在少数吧

2022-02-23 04:48 UTC, Anduin2017 commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* �Σ����ף�
一个勺子20ml，这是相当大的勺子了

2022-02-23 09:09 UTC, Whatever-An commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* �Σ����ף�
已处理

2022-02-23 09:09 UTC, Whatever-An commented on dishes/home-cooking/鱼香茄子/鱼香茄子.md
> +* ���е���300ml�ͣ��������߳��ȣ�����ð���������ը����ӣ������ӱ�Ե΢�ƾ��̳�����Ϳ���ʢ���Ժ󳴲��á�
已处理

2022-02-23 09:13 UTC, MESOLONELY approved these changes
Looks better

2022-02-23 12:24 UTC, merged