添加红烧日本豆腐做法
Anduin2017/HowToCook pull request #336
Opened 2022-02-22 15:01 UTC by Mrhs121

## 修改类型

这个 Pull Request 是在：

- [x] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [x] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [x] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [x] 我没有破坏模板的一二级标题格式。
- [x] 我没有删除模板中必需的内容。
- [x] 我已删除干净所有的复制出来的模板的注释。
- [x] 我确保我没有签入任何和版权方相关的内容、图片。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-22 15:07 UTC, anois commented
您好，感谢贡献！但是看起来它的内容格式和约束的标准差距很大。请您重新从[模板文件](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1)复制来得到空菜谱，再修改内容为您的菜谱。不要直接编写新的文件。您先改改我再重新review。

2022-02-22 15:43 UTC, Mrhs121 commented
改好了

2022-02-23 06:53 UTC, Anduin2017 requested changes
请不要checkin菜谱之外的文件。例如.DS_Store

2022-02-23 06:57 UTC, Mrhs121 commented
rm .DS_Store

2022-02-23 06:59 UTC, Anduin2017 requested changes
文件路径。

2022-02-23 06:59 UTC, Anduin2017 commented on README.md
> +* [红烧日本豆腐](./dishes/home-cooking/红烧日本豆腐.md)
这不是红烧菜么，你确定放在这个文件夹？

2023-05-13 15:34 UTC, closed without merging