奇异果菠菜特调
Anduin2017/HowToCook pull request #382
Opened 2022-02-23 05:12 UTC by Aubrey-M-ops

## 修改类型

这个 Pull Request 是在：

- [x] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [x] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [x] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [x] 我没有破坏模板的一二级标题格式。
- [x] 我没有删除模板中必需的内容。
- [x] 我已删除干净所有的复制出来的模板的注释。
- [x] 我确保我没有签入任何和版权方相关的内容、图片。

## 警告

**HowToCook 仓库采用了 [[The Unlicense](https://unlicense.org/)](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-23 06:41 UTC, Anduin2017 requested changes
原生markdown

2022-02-23 06:41 UTC, Anduin2017 commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +<img src="./kiwi-example.jpg" style="zoom:20%;" /> |
使用原生markdown，方便后续的机器处理。

2022-02-23 06:56 UTC, Anduin2017 requested changes
使用原生markdown。方便后续的机器处理。

2022-02-23 06:56 UTC, Anduin2017 commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +<img src="./kiwi-example.jpg" style="zoom:20%;" />
使用原生markdown。

2022-02-23 07:00 UTC, Aubrey-M-ops commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +<img src="./kiwi-example.jpg" style="zoom:20%;" />
这回改了🥲

2022-02-23 07:08 UTC, Anduin2017 requested changes
存在不精准的单位。

2022-02-23 07:08 UTC, Anduin2017 commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +- 白砂糖的量按照个人喜好添加即可
量化添加的范围。

2022-02-23 07:08 UTC, Anduin2017 commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +- 白砂糖一勺
勺不是一个精准的单位。#347

2022-02-23 07:11 UTC, Aubrey-M-ops commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +- 白砂糖一勺
已改正

2022-02-23 07:16 UTC, Anduin2017 approved these changes

2022-02-23 07:17 UTC, Anduin2017 requested changes
请给出添加的范围。例如全糖是12g，可以在0-12g中调整。

2022-02-23 07:17 UTC, Anduin2017 commented on dishes/drink/奇异果菠菜特调/奇异果菠菜特调.md
> +- 白砂糖的量按照个人喜好添加即可
请给出添加的范围。例如全糖是12g，可以在0-12g中调整。

2022-03-04 16:21 UTC, Anduin2017 approved these changes

2022-03-04 16:22 UTC, Anduin2017 approved these changes

2022-03-07 05:10 UTC, merged