Create 口水鸡.md
Anduin2017/HowToCook pull request #408
Opened 2022-02-23 09:01 UTC by leader402

## 修改类型

这个 Pull Request 是在：

- [✓ ] 增加菜谱

## 检查单

- [ ✓ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ ✓ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [✓  ] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [ ✓ ] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [ ✓ ] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [ ✓ ] 我没有破坏模板的一二级标题格式。
- [ ✓ ] 我没有删除模板中必需的内容。
- [✓  ] 我已删除干净所有的复制出来的模板的注释。
- [ ✓ ] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-23 17:35 UTC, Anduin2017 requested changes
图片格式。

2022-02-23 17:35 UTC, Anduin2017 commented on dishes/home-cooking/口水鸡.md
> +![口水鸡](https://user-images.githubusercontent.com/47787078/155281540-f7fda9bf-6ae2-43a7-90ea-b656fc2f148e.jpg)
不要用绝对路径！不要从CDN中引用图片！

2022-02-24 03:12 UTC, leader402 commented on dishes/home-cooking/口水鸡.md
> +![口水鸡](https://user-images.githubusercontent.com/47787078/155281540-f7fda9bf-6ae2-43a7-90ea-b656fc2f148e.jpg)
已更新图片路径，上传图片，更改readme。

2022-02-24 04:08 UTC, Anduin2017 requested changes
有错误

2022-02-24 04:08 UTC, Anduin2017 commented on dishes/home-cooking/口水鸡.md
> +- 姜       1小块
重量。

2022-02-24 04:08 UTC, Anduin2017 commented on dishes/home-cooking/口水鸡.md
> +- 将热油导入城防辣椒粉的碗中，搅拌，并滤出红油
城防？？？

2022-02-24 06:31 UTC, leader402 commented on dishes/home-cooking/口水鸡.md
> +- 将热油导入城防辣椒粉的碗中，搅拌，并滤出红油
错别字已修改，重量已备注

2022-02-24 06:35 UTC, Anduin2017 requested changes
为什么签入了两个口水鸡.md

2022-02-24 06:35 UTC, Anduin2017 commented on dishes/home-cooking/口水鸡/口水鸡.md
> +# 口水鸡的做法
为什么签入了两个口水鸡.md

2022-02-24 06:41 UTC, leader402 commented on dishes/home-cooking/口水鸡/口水鸡.md
> +# 口水鸡的做法
上午删除失败，已删除多余口水鸡.md

2022-02-24 16:01 UTC, Anduin2017 requested changes
不要删除模板中必需的内容。

2022-02-24 16:09 UTC, leader402 commented on dishes/home-cooking/口水鸡/口水鸡.md
> +
已添加，必须内容

2022-02-25 06:32 UTC, Anduin2017 approved these changes

2022-02-25 06:33 UTC, merged