feature: 微波炉腊肠煲仔饭
Anduin2017/HowToCook pull request #419
Opened 2022-02-23 11:20 UTC by lcomplete

## 修改类型

这个 Pull Request 是在：

- [x] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [x] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [x] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [x] 我没有破坏模板的一二级标题格式。
- [x] 我没有删除模板中必需的内容。
- [x] 我已删除干净所有的复制出来的模板的注释。
- [x] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-23 12:45 UTC, MESOLONELY requested changes
感谢你的贡献! 不过还有一些仓库的规范性问题还望得到你的修改

2022-02-23 12:45 UTC, MESOLONELY commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +- 将米淘洗干净后倒入 `饭碗` 内，加入平时做饭所需要的 `2/3` 的水，**盖上盖**
「加入平时做饭所需要的 `2/3` 的水」建议修改为大致毫升数, 如 100 ~ 120 ml 水

2022-02-23 12:45 UTC, MESOLONELY commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - 葱花少许
请避免「少许」等词的出现, 而使用「克」, 如: 9-10g. 参考[示例菜中的说明](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1#L47)

2022-02-23 12:45 UTC, MESOLONELY commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - `小碗` 中倒入少许生抽、几滴油
避免「少许, 几滴」等词的出现

2022-02-23 12:45 UTC, MESOLONELY commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - `青菜碗` 中放入青菜，红萝卜片，倒入几滴油，放入一小勺盐
避免「一小勺」等词的出现, 参考[示例菜中勺的说明](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md?plain=1#L42)

2022-02-24 02:58 UTC, lcomplete commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - 葱花少许
已修改。

2022-02-24 02:59 UTC, lcomplete commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - `小碗` 中倒入少许生抽、几滴油
已修改。

2022-02-24 02:59 UTC, lcomplete commented on dishes/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md
> +  - `青菜碗` 中放入青菜，红萝卜片，倒入几滴油，放入一小勺盐
已修改。

2022-02-24 04:11 UTC, Anduin2017 approved these changes

2022-02-24 04:11 UTC, merged