update  油泼辣子.md
Anduin2017/HowToCook pull request #432
Opened 2022-02-23 14:31 UTC by leo220yuyaodog

辣椒面原本15克，油40克，在一次制作中过于少，原不足一次制作耗费精力。一般家用的做一次油泼辣子，酌情100克-200左右。
必备原料和工具中，白芝麻 强调为 熟白芝麻
新增附加内容，油泼辣子可选的提升香味的一些原料
## 修改类型

这个 Pull Request 是在：

- [ ] 增加菜谱
- [ ] 修复错误
- [x] 其它

## 检查单

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [x] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [x] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [x] 我没有破坏模板的一二级标题格式。
- [x] 我没有删除模板中必需的内容。
- [x] 我已删除干净所有的复制出来的模板的注释。
- [x] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-23 17:19 UTC, Anduin2017 requested changes
不明确。

2022-02-23 17:19 UTC, Anduin2017 commented on dishes/condiment/油泼辣子.md
> +- 五香粉（桂皮，香叶，大茴香，肉蔻磨制） 10 克
为什么附加内容里放了个五香粉？是指的是可以添加嘛？什么时候添加？

2022-02-24 01:08 UTC, leo220yuyaodog commented
五香粉的添加写入了操作中

2022-02-24 01:15 UTC, leo220yuyaodog commented on dishes/condiment/油泼辣子.md
> +- 五香粉（桂皮，香叶，大茴香，肉蔻磨制） 10 克
问题我已经解决的，完善添加的位置

2022-02-24 04:19 UTC, Anduin2017 approved these changes

2022-02-24 04:19 UTC, merged