新增酸梅汤
Anduin2017/HowToCook pull request #466
Opened 2022-02-24 08:41 UTC by ITdesk01

Signed-off-by: ITdesk01 <ITdesk01>

## 修改类型

这个 Pull Request 是在：

- [x ] 增加菜谱
- [ ] 修复错误
- [ ] 其它

2022-02-24 15:57 UTC, Anduin2017 requested changes
请基于模板创建。使用原生markdown语法。

2022-02-24 15:57 UTC, Anduin2017 commented on dishes/drink/酸梅汤/酸梅汤.md
> +| 成品   | <img src="./imges/sour_plum_soup.jpg" style="zoom:20%;" />  |
请基于模板创建。使用原生markdown语法。

2022-02-25 08:53 UTC, ITdesk01 commented
我是根据你仓库里的酸梅汤模板修改的，你现在有啥需要我修改的？？能指明出来？？

2022-02-25 09:07 UTC, Anduin2017 requested changes
请不要签入html！

2022-02-25 09:12 UTC, ITdesk01 commented
> 请不要签入html！

已经更新了，这个我是抄百香果橙子特调的.md,我以为可以加的

2022-02-25 09:14 UTC, Anduin2017 approved these changes

2022-02-25 09:14 UTC, merged