create 荤菜/红烧猪蹄
Anduin2017/HowToCook pull request #468
Opened 2022-02-24 09:11 UTC by wz930206

## 修改类型

这个 Pull Request 是在：

- [ √ ] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [ √ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ √ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [ √ ] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [ √ ] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [√ ] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [√ ] 我没有破坏模板的一二级标题格式。
- [√ ] 我没有删除模板中必需的内容。
- [ √] 我已删除干净所有的复制出来的模板的注释。
- [√ ] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-24 15:56 UTC, Anduin2017 requested changes
勺 不是合理的单位。

2022-02-24 15:56 UTC, Anduin2017 commented on dishes/home-cooking/红烧猪蹄/红烧猪蹄.md
> +- 料酒 4 勺
勺 不是合理的单位。

2022-02-25 01:35 UTC, wz930206 reviewed
勺精确化

2022-02-25 06:27 UTC, Anduin2017 approved these changes

2022-02-25 06:28 UTC, Anduin2017 requested changes
这是个荤菜吧

2022-02-25 06:28 UTC, Anduin2017 commented on README.md
> +* [菌菇炖乳鸽](./dishes/soup/菌菇炖乳鸽/菌菇炖乳鸽.md)
这是个荤菜吧

2022-02-25 06:28 UTC, wz930206 commented on README.md
> +* [菌菇炖乳鸽](./dishes/soup/菌菇炖乳鸽/菌菇炖乳鸽.md)
不是，是汤，就像老母鸡汤一样

2022-02-25 06:39 UTC, Anduin2017 requested changes
那要么放在 汤和粥 的分类里。

2022-02-25 06:39 UTC, Anduin2017 commented on README.md
> +* [菌菇炖乳鸽](./dishes/soup/菌菇炖乳鸽/菌菇炖乳鸽.md)
那要么放在 汤和粥 的分类里。

2022-02-25 06:42 UTC, wz930206 commented on README.md
> +* [菌菇炖乳鸽](./dishes/soup/菌菇炖乳鸽/菌菇炖乳鸽.md)
菌菇炖乳鸽 我是放在 汤与粥的分类里的

2022-02-25 07:36 UTC, wz930206 commented
你那边看到的不是在汤和粥的分类吗，我这边是的
![image](https://user-images.githubusercontent.com/37261842/155674331-f55b6618-e00b-48eb-9a99-965c22defe14.png)

2022-02-25 09:08 UTC, Anduin2017 approved these changes

2022-02-25 09:09 UTC, merged