增加菜谱
Anduin2017/HowToCook pull request #470
Opened 2022-02-24 10:17 UTC by ChinaLeng

- [ ] 增加菜谱

2022-02-24 15:55 UTC, Anduin2017 requested changes
需要更加精准。

2022-02-24 15:55 UTC, Anduin2017 commented on dishes/home-cooking/鳊鱼炖豆腐/鳊鱼炖豆腐.md
> +- 葱：半根
需要更加精准。

2022-02-25 01:48 UTC, ChinaLeng commented
修改用料数量

2022-02-25 05:50 UTC, Anduin2017 requested changes
这不应该放在水产的分类里么。

2022-02-25 05:50 UTC, Anduin2017 commented on README.md
> +* [鳊鱼炖豆腐](./dishes/home-cooking/鳊鱼炖豆腐/鳊鱼炖豆腐.md)
这不应该放在水产的分类里么。

2022-02-25 06:39 UTC, Anduin2017 requested changes
需要更加精准。

2022-02-25 06:39 UTC, Anduin2017 commented on dishes/home-cooking/鳊鱼炖豆腐/鳊鱼炖豆腐.md
> +- 老抽：1勺(不太喜欢重口的可以不放)
给出毫升数。

2022-02-25 09:11 UTC, Anduin2017 approved these changes

2022-02-25 09:11 UTC, merged