feat:烤鱼
Anduin2017/HowToCook pull request #471
Opened 2022-02-24 10:47 UTC by lalwaysy

## 修改类型

这个 Pull Request 是在：

- [ ] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [ ] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [ ] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [ ] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [ ] 我没有破坏模板的一二级标题格式。
- [ ] 我没有删除模板中必需的内容。
- [ ] 我已删除干净所有的复制出来的模板的注释。
- [ ] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-24 15:54 UTC, Anduin2017 requested changes
更新 Readme 对本次修改的菜谱的引用链接

2022-02-25 02:02 UTC, TusiziLy commented
已添加

2022-02-25 05:49 UTC, Anduin2017 requested changes
这不应该放在水产那里么。

2022-02-25 05:49 UTC, Anduin2017 commented on README.md
> +* [烤鱼](./dishes/home-cooking/混合烤鱼/烤鱼.md)
这不应该放在水产那里么。

2022-02-25 05:52 UTC, TusiziLy commented on README.md
> +* [烤鱼](./dishes/home-cooking/混合烤鱼/烤鱼.md)
这家常菜呀，我看很多人也是做的鱼也放在这个里面

2022-02-25 06:38 UTC, Anduin2017 requested changes
放在 家常菜\水产 目录下。

2022-02-25 06:38 UTC, Anduin2017 commented on README.md
> +* [烤鱼](./dishes/home-cooking/混合烤鱼/烤鱼.md)
放在 家常菜\水产 目录下。

2022-02-25 06:38 UTC, TusiziLy commented on README.md
> +* [烤鱼](./dishes/home-cooking/混合烤鱼/烤鱼.md)
好吧哈哈哈哈

2022-02-25 06:43 UTC, TusiziLy commented on README.md
> +* [烤鱼](./dishes/home-cooking/混合烤鱼/烤鱼.md)
已修改

2022-02-25 09:13 UTC, Anduin2017 requested changes
需要更加精准。

2022-02-25 09:13 UTC, Anduin2017 commented on dishes/home-cooking/混合烤鱼/烤鱼.md
> +- 锅中撒上 20ml食用油，等到油热后，把大葱大蒜八角香叶倒入炒香，加上一半火锅底料和一勺豆瓣酱，炒出红油后，加入少许白糖，10g食盐，少许生抽调味，倒入和食材齐平的清水煮开，依次下入芹菜段，豆芽，千张丝，不用煮熟，稍微烫一下后铺上洋葱丝，放上烤鱼，加入干辣椒，灯笼椒，青花椒，另一个锅烧油，油热后浇在刚加入的辣椒上面激发出香味，最后撒上熟花生米，葱花，白芝麻，香菜，煮五六分钟，美味即成。
勺子是不规范的单位。可能有歧义。

2022-02-25 09:37 UTC, Anduin2017 approved these changes

2022-02-25 09:38 UTC, merged