新增煎饺的做法
Anduin2017/HowToCook pull request #535
Opened 2022-02-27 02:32 UTC by Wy620

## 修改类型

这个 Pull Request 是在：

- [x] 增加菜谱
- [x] 修复错误
- [ ] 其它

## 检查单

- [x] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [x] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [x] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [x] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [x] 我已更新 Readme 对本次修改的菜谱的引用链接。
- [x] 我没有破坏模板的一二级标题格式。
- [ ] 我没有删除模板中必需的内容。
- [x] 我已删除干净所有的复制出来的模板的注释。
- [x] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-27 02:33 UTC, Wy620 commented
新增煎饺的做法

2022-02-27 06:06 UTC, Anduin2017 requested changes
删除注释。

2022-02-27 06:26 UTC, Anduin2017 requested changes
一些小问题。

2022-02-27 06:26 UTC, Anduin2017 commented on dishes/breakfast/煎饺.md
> +- 饺子一包 （根据个人食量选择）
建议补充一下个数范围吧。

2022-02-27 06:26 UTC, Anduin2017 commented on dishes/breakfast/煎饺.md
> +- 加入清水，没过饺子 1/2
刚放油就放水吗？煎多久呢。

2022-02-27 06:26 UTC, Anduin2017 commented on dishes/breakfast/煎饺.md
> +- 操作时，需时刻观察锅内情况，切记不可分神玩手机。
不要删除模板中必需的内容。

2022-02-28 07:30 UTC, liruiqiang666 commented
出锅前放入黑芝麻和葱花再焖10s更香哦

2022-02-28 16:43 UTC, Anduin2017 commented
@Wy620 请修正PR中的问题。我们将重新review。

2022-02-28 16:50 UTC, Wy620 commented
已修正

2022-02-28 18:27 UTC, merged