添加鸡蛋豆腐菜单，重点是补肾大补超级补！！！
Anduin2017/HowToCook pull request #545
Opened 2022-02-28 02:08 UTC by 531431988

## 修改类型

这个 Pull Request 是在：

- [ ] 增加菜谱
- [ ] 修复错误
- [ ] 其它

## 检查单

- [ ] 我已阅读贡献模板，并按照模板规范进行了内容创作。
  - [ ] 菜谱包含`必备原料和工具`, `计算`, `操作`三部分内容。
  - [ ] 菜品的`原材料用量`是无歧义且准确的。对于可以自行发挥的量给出了建议的范围。
  - [ ] 菜品的`制作步骤`是无歧义，准确且完整的。对于每一个步骤的开始和结束都有明确的标准。
- [ ] 我没有破坏模板的一二级标题格式。
- [ ] 我没有删除模板中必需的内容。
- [ ] 我已删除干净所有的复制出来的模板的注释。
- [ ] 我确保我没有签入任何和版权方相关的内容、图片。

请审核人员按照 [审核检查单](https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%AE%A1%E6%A0%B8%E5%91%98%E9%A1%BB%E7%9F%A5) 对照审核检查。

## 警告

**HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议！**

**菜谱在签入前，必须确保其可以直接声明进入 "公共领域"（public domain)。这意味着一旦合并后，任何人都可以自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，无论是出于商业目的还是非商目的，以及任何手段。**

2022-02-28 03:48 UTC, Anduin2017 requested changes
不太精准。

2022-02-28 03:48 UTC, Anduin2017 commented on dishes/home-cooking/鸡蛋豆腐/鸡蛋豆腐.md
> +- 小米椒 2个（喜欢辣的可以多放两个）
重量参考范围。

2022-02-28 03:48 UTC, Anduin2017 commented on dishes/home-cooking/鸡蛋豆腐/鸡蛋豆腐.md
> +- 老豆腐一块（不知道重量都是按块卖，武汉大概3块钱一块）
重量参考范围。

2022-02-28 06:14 UTC, 531431988 commented on dishes/home-cooking/鸡蛋豆腐/鸡蛋豆腐.md
> +- 老豆腐一块（不知道重量都是按块卖，武汉大概3块钱一块）
建议各位想参照这个做菜先买个天平和量杯，不然就别做了，太苛刻了！我都是哔哩哔哩里面学的，说实话根本不用这么苛刻，一个菜做几次就掌握了技巧，而且通用，按这种苛刻的手法我就问别人讲究的火候，你怎么控制？大中小火？控制一下出燃气量吗？

2022-02-28 18:26 UTC, Anduin2017 commented on dishes/home-cooking/鸡蛋豆腐/鸡蛋豆腐.md
> +- 老豆腐一块（不知道重量都是按块卖，武汉大概3块钱一块）
https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md#%E5%86%85%E5%AE%B9%E8%A7%84%E8%8C%83

2022-03-02 19:26 UTC, Anduin2017 commented
https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md#%E4%BB%93%E5%BA%93%E5%8E%9F%E5%88%99

2025-04-18 01:36 UTC, abandon-jw3 commented
我一个朋友需要这个菜

2025-04-23 10:25 UTC, closed without merging