分类 顺便测试ci机器人能否运行
Anduin2017/HowToCook pull request #575
Opened 2022-03-02 00:38 UTC by WakiJi

2022-03-02 18:23 UTC, Anduin2017 requested changes
Conflict.

2022-03-02 18:56 UTC, Anduin2017 commented
@WakiJi 话说，大佬，说句题外话就是……

您看这个文件也能做个脚本来自动生成一下嘛  https://github.com/Anduin2017/HowToCook/blob/master/mkdocs.yml

2022-03-03 02:06 UTC, WakiJi commented
> @WakiJi 话说，大佬，说句题外话就是……
> 
> 您看这个文件也能做个脚本来自动生成一下嘛  https://github.com/Anduin2017/HowToCook/blob/master/mkdocs.yml

非常抱歉，对这一块我不太熟，我现有的知识水平似乎不允许我完成这个任务

2022-03-03 04:20 UTC, Anduin2017 approved these changes

2022-03-03 04:42 UTC, merged