更新了西红柿鸡蛋
Anduin2017/HowToCook pull request #77
Opened 2022-02-18 10:38 UTC by Sodium-Aluminate

你们西红柿炒鸡蛋都不去皮的吗？

2022-02-18 11:03 UTC, monkeylord commented
+1
西红柿得去皮

蛋液中根据口味可以加一点点胡椒粉提味
鸡蛋如果想要蓬松一点就大火炒
鸡蛋如果想要滑嫩一点就10S后关火炒20S

2022-02-18 15:50 UTC, Howard20181 commented
表示还真的不去皮，根据个人喜好的吧

因为皮上含有丰富的番茄红素，为了防止营养流失就保留

不过如果不是非常新鲜的或者是催熟的或者皮比较厚的那就没办法

2022-02-18 16:22 UTC, Anduin2017 requested changes
感觉大部分没有问题。除了有些通用的工具我直接写在Readme的必备区了。

2022-02-18 16:22 UTC, Anduin2017 commented on 西红柿鸡蛋.md
> +* 清水（视情况可选择自来水或饮用水）
饮用水已经出现在Readme的必备区了。

2022-02-18 16:22 UTC, Anduin2017 commented on 西红柿鸡蛋.md
> +* 容器（熟食）
生熟容器看起来非常常用。可以直接修改Readme的必备餐具区。

2022-02-18 16:22 UTC, Anduin2017 commented on 西红柿鸡蛋.md
> +* 刀
菜刀已经添加到必备餐具区。不需要再在菜谱中指明。

2022-02-18 17:46 UTC, Anduin2017 commented on 西红柿鸡蛋.md
> +  * 鸡蛋的数量并不需要严格对应，可根据个人喜好增加鸡蛋的量。
增加几个？这里应该给出一个范围

2022-02-18 17:47 UTC, Anduin2017 commented on 西红柿鸡蛋.md
> +* 如果有炝锅用葱，带油温升高后加入葱花。
typo 待

2022-02-19 16:02 UTC, Anduin2017 commented
西红柿鸡蛋已经被重构。抱歉这个PR无法被合并。如果对重构后的西红柿炒鸡蛋有任何建议，请提交新的PR。

2022-02-19 16:02 UTC, closed without merging