Add: 速冻水饺
Anduin2017/HowToCook pull request #85
Opened 2022-02-18 14:07 UTC by iceBear67

~~加水是我爸教我的~~  
水个 PR

2022-02-18 15:47 UTC, Howard20181 commented
后面加水重复3-5次是为什么

2022-02-18 15:50 UTC, iceBear67 commented
貌似真有依据（  
https://www.zhihu.com/question/27911488

2022-02-18 15:58 UTC, iceBear67 commented
但是直接下锅还是有点粘的啊（    
其实过水是为了洗掉上面的面粉（?) 之类的东西，不然煮的时候锅里会白茫茫一片
~~关于加冷水我感觉大半只是为了让饺子煮旧一点~~

2022-02-18 16:17 UTC, Howard20181 commented
外面的面粉是为了防止黏连才放的 

知乎上的答案也说了是以前烧柴不好控制防止暴沸才加冷水的

2022-02-18 16:17 UTC, iceBear67 commented
好吧，我早上改一下

2022-02-18 16:19 UTC, Anduin2017 approved these changes

2022-02-18 16:19 UTC, Anduin2017 requested changes
有社区里的一些review。按照他们大佬的修改吧

2022-02-19 04:02 UTC, Anduin2017 approved these changes

2022-02-19 15:55 UTC, merged

2022-06-15 02:32 UTC, HuWenjin commented
这可是高知程序员地盘 你们试过没有? 开锅后加水 和小火慢煮 各自得到什么结果. 煮饭并不是煮熟了就行 还要让别人吃得下去