改进计算菜的数量的算法
Anduin2017/HowToCook pull request #94
Opened 2022-02-19 00:54 UTC by qyl27

一般多人聚会或自己做饭宴请他人时，菜的数量应当是偶数（若是在做祭祀，菜的数量应当是奇数）。
此外单人食用时，两道菜可能有些多。
~~形式语言描述我不会写，所以添加了程序语言描述（x~~
todo: 集成吃什么选择器。
~~（水个pr）~~

2022-02-19 07:01 UTC, qyl27 commented
改成分情况讨论（x

2022-02-19 08:55 UTC, Anduin2017 commented on 如何选择现在吃什么.md
> +* 菜的数量 = 1。
感觉吃不饱？

2022-02-19 08:55 UTC, Anduin2017 requested changes
感觉一个人吃有点儿吃不饱？

2022-02-19 08:58 UTC, qyl27 commented
> 感觉一个人吃有点儿吃不饱？

啊……吃菜不应该还需要一点主食吗？而且，一道菜只有一个人吃就会很饱了吧qwq（最起码我是这样（当然有可能要看地区差异……北方的盘子可能大一些？（x

2022-02-19 10:46 UTC, Anduin2017 commented on 如何选择现在吃什么.md
>  * 菜的数量 = 人数 + 1。
感觉有点儿奇怪：两个人时需要3个菜，一个人就只需要1个菜

2022-02-19 10:47 UTC, qyl27 commented on 如何选择现在吃什么.md
>  * 菜的数量 = 人数 + 1。
好像是个bug……（现在想不出怎么处理了

2022-02-19 10:54 UTC, recolic commented on 如何选择现在吃什么.md
>  * 菜的数量 = 人数 + 1。
我一般是一个人1个菜（因为吃饱了就行）。但两个人就要3个菜了，这样显得比较隆重（不是）比较丰富多样

2022-02-19 13:12 UTC, Anduin2017 commented
这个PR没啥大问题了我感觉。唯一不爽的就是这个分段函数分了三段。如果能分两段或一段就最好了。

2022-02-19 13:12 UTC, Anduin2017 commented
注意lint没过：

```log
Run mdl *.md -r ~MD029,~MD036,~MD02[4](https://github.com/Anduin2017/HowToCook/runs/5258405087?check_suite_focus=true#step:4:4)
如何选择现在吃什么.md:10: MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:14: MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:18: MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:36: MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:41: MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:4[5](https://github.com/Anduin2017/HowToCook/runs/5258405087?check_suite_focus=true#step:4:5): MD032 Lists should be surrounded by blank lines
如何选择现在吃什么.md:4[9](https://github.com/Anduin2017/HowToCook/runs/5258405087?check_suite_focus=true#step:4:9): MD032 Lists should be surrounded by blank lines

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
```

2022-02-20 00:50 UTC, qyl27 commented
现在lint修好了

2022-02-20 04:18 UTC, Anduin2017 commented
但是conflict

2022-02-20 07:54 UTC, qyl27 commented
那咋办qwq

2022-02-20 08:32 UTC, closed without merging